### ISSUE TITLE
Ability to include Job pods

### ISSUE THREAD

**Issue by jacobsvante** [eht16/kube-cargo-load#2]
First of all - Thanks for creating this project!

Just throwing out a suggestion - what about being able to see Jobs as well? Their resource usage may also be interesting to look at 😊

**Comment by eht16** [comment]
I agree.
For some reason, `kubectl top pods` does not return PODs which were created by Jobs.
Even explicitly querying a POD by `kubectl top pod hello-1589544000-27m8x` (where `hello-1589544000-27m8x` is just a test POD) just gives:

`Error from server (NotFound): podmetrics.metrics.k8s.io "default/hello-1589544000-27m8x" not found`

In the logs of the `metrics-server` there is a corresponding error:

`E0515 23:38:06.467447       1 reststorage.go:133] unable to fetch pod metrics for pod default/hello-1589544000-27m8x: no metrics known for pod "default/hello-1589544000-27m8x"`

My test POD was running for two minutes, so that `metrics-server` should have had a chance to see the POD running.
So it seems `metrics-server` does not support collecting metrics of Job-PODs or I just don't know how.

**Comment by eht16** [comment]
I had another look at this:
the `metrics-server` *does* monitor PODS created by a job but only while they are running.
This is by design of the `metrics-server` as its purpose is to provide realtime metrics of PODs (and nodes) but not to provide historical data. And it does not differentiate between PODs created by a deployment, job or whatever.

While this is sad for the use case here, I think it is a proper behaviour in general. Otherwise `metrics-server` probably would have to carry a lot of historical data and need to maintain it somehow.
`kube-cargo-load` also just displays the realtime metrics provided by the API. For anything beyond, a proper monitoring system is needed.
